import os
import tkinter as tk
import tkinter.ttk as ttk
import pygubu
import Programa
import CadastroEquip,CadastroEquipDes,CadastrarDesativacao,CadastrarEsporadica,CadastrarMovimentacao,CadastrarPreventiva,CadastrarReentrada,CadastroCalibr,JanelaProc,PopUpAlarme,Intervalos
import AvisoSucess

#PROJECT_PATH = os.path.abspath(os.path.dirname(__file__))
#PROJECT_UI = os.path.join(PROJECT_PATH, "inicial.ui")

class InicialApp:
    def __init__(self, master=None):
        # build ui
        self.toplevel1 = tk.Toplevel()
        
        self.toplevel1.title("Exibir Todos")
        self.frame2 = tk.Frame(self.toplevel1)
        self.treeview1 = ttk.Treeview(self.frame2)
        self.treeview1.place(anchor='nw', height='615', relx='0.13', rely='0.12', width='1130', x='0', y='0')
        self.scrollbar1 = ttk.Scrollbar(self.frame2)
        self.scrollbar1.configure(orient='horizontal',command=self.treeview1.xview)
        self.scrollbar1.place(anchor='nw', relx='0.13', rely='0.977', width='1130', x='0', y='0')
        self.treeview1.configure(xscroll=self.scrollbar1.set)
        
        self.scrollbar2 = ttk.Scrollbar(self.frame2)
        self.scrollbar2.configure(orient='vertical',command=self.treeview1.yview)
        self.scrollbar2.place(anchor='nw', height='615', relx='0.987', rely='0.12', x='0', y='0')
        self.treeview1.configure(yscroll=self.scrollbar2.set)
        
        self.button11 = tk.Button(self.frame2)
        self.button11.configure(text='Calibrações')
        self.button11.place(anchor='nw', relx='0.013', rely='.20', width='150', x='0', y='0')
        self.button11.configure(command=self.Calibri_view)
        self.button11.configure(command=lambda:[self.limpartree(), self.Calibri_view()])
        
        self.button12 = tk.Button(self.frame2)
        self.button12.configure(text='Preventivas')
        self.button12.place(anchor='nw', relx='0.013', rely='0.25', width='150', x='0', y='0')
        self.button12.configure(command=self.Prevent_view)
        self.button12.configure(command=lambda:[self.limpartree(), self.Prevent_view()])
        
        self.button13 = tk.Button(self.frame2)
        self.button13.configure(text='Esporádicas')
        self.button13.place(anchor='nw', relx='0.013', rely='.30', width='150', x='0', y='0')
        self.button13.configure(command=self.Esporadica_view)
        self.button13.configure(command=lambda:[self.limpartree(), self.Esporadica_view()])
        
        self.button14 = tk.Button(self.frame2)
        self.button14.configure(text='Retornos')
        self.button14.place(anchor='nw', relx='0.013', rely='.35', width='150', x='0', y='0')
        self.button14.configure(command=self.Reentrada_view)
        self.button14.configure(command=lambda:[self.limpartree(), self.Reentrada_view()])
        
        self.button15 = tk.Button(self.frame2)
        self.button15.configure(text='Movimentações')
        self.button15.place(anchor='nw', relx='0.013', rely='.40', width='150', x='0', y='0')
        self.button15.configure(command=self.Movi_view)
        self.button15.configure(command=lambda:[self.limpartree(), self.Movi_view()])

        self.button16 = tk.Button(self.frame2)
        self.button16.configure(text='Fabricantes')
        self.button16.place(anchor='nw', relx='0.013', rely='.45', width='150', x='0', y='0')
        self.button16.configure(command=self.Movi_view)
        self.button16.configure(command=lambda:[self.limpartree(), self.Fabri_view()])

        self.button17 = tk.Button(self.frame2)
        self.button17.configure(text='Alterar Intervalos')
        self.button17.place(anchor='nw', relx='0.013', rely='.9', width='150', x='0', y='0')
        self.button17.configure(command=Intervalos.abre)
        
        self.label1 = ttk.Label(self.frame2)
        self.cap_PNG = tk.PhotoImage(file='logo.PNG')
        self.label1.configure(background='#a5d6ef', cursor='gumby', image=self.cap_PNG)
        self.label1.place(anchor='nw', height='100', relx='0.013', rely='0.01', width='150', x='0', y='0')
        self.label2 = ttk.Label(self.frame2)
        self.label2.configure(background='#a5d6ef', font='{eras demi itc} 36 ', text='SHProgram')
        self.label2.place(anchor='nw', relx='0.146', rely='0.02', x='0', y='0')
        self.label3 = ttk.Label(self.frame2)
        self.label3.configure(borderwidth='5', font='{arial} 20 {}', relief='groove', text='HMCC')
        self.label3.place(anchor='nw', relx='0.63', rely='0.04', x='0', y='0')

        '''self.lblCadastrante = tk.Label(self.frame2)
        self.lblCadastrante.configure(background='#a5d6ef', font='{arial} 12 {bold underline}', foreground='#ff0000')
        self.lblCadastrante.place(anchor='nw', relx='0.9', rely='0.00', x='0', y='0')
        self.lblCadastrante.configure(text=(Programa.logado[0]))'''
        
        self.frame2.configure(background='#a5d6ef', borderwidth='5', height=730,width=1330,relief='sunken')
        self.frame2.place(anchor='nw', relx='0.003', rely='0.003', x='0', y='0')
        
        self.toplevel1.configure(background='#669bdb', borderwidth='5', height=700, width=1350, relief='raised')

        app_width =1350
        app_height =750

        screen_width =self.toplevel1.winfo_screenwidth()
        screen_height=self.toplevel1.winfo_screenheight()

        x = (screen_width/2)-(app_width/2)
        y = (screen_height/2)-(app_height/2)

        self.toplevel1.geometry(f'{app_width}x{app_height}+{int(x)}+{int(y)}')

        # Main widget
        self.mainwindow = self.toplevel1

    def limpartree(self):
        self.treeview1.delete(*self.treeview1.get_children())

    def Calibri_view(self):
        self.label3.configure(text='Calibrações')
        self.treeview1['columns']=('c1','c2','c3','c4','c5','c6','c7','c8','c9','c10','c11','c12','c13','c14')
        self.treeview1.column('#0',width=0)
        self.treeview1.column('c1',width=100)
        self.treeview1.column('c2',width=100)
        self.treeview1.column('c3',width=100)
        self.treeview1.column('c4',width=100)
        self.treeview1.column('c5',width=130)
        self.treeview1.column('c6',width=100)
        self.treeview1.column('c7',width=100)
        self.treeview1.column('c8',width=100)
        self.treeview1.column('c9',width=130)
        self.treeview1.column('c10',width=100)
        self.treeview1.column('c11',width=130)
        self.treeview1.column('c12',width=130)
        self.treeview1.column('c13',width=100)
        self.treeview1.column('c14',width=100)
        self.treeview1.heading('#0',text='')
        self.treeview1.heading('#1',text='Tipo')
        self.treeview1.heading('#2',text='Patrimônio')
        self.treeview1.heading('#3',text='Número de Série')
        self.treeview1.heading('#4',text='Data de Retirada')
        self.treeview1.heading('#5',text='Acessórios Retirados')
        self.treeview1.heading('#6',text='Andar Retirado')
        self.treeview1.heading('#7',text='Setor Retirado')
        self.treeview1.heading('#8',text='Local Retirado')
        self.treeview1.heading('#9',text='Empresa Responsável')
        self.treeview1.heading('#10',text='Técnico')
        self.treeview1.heading('#11',text='Ordem de Serviço')
        self.treeview1.heading('#12',text='Enfermeira Reponsável')
        self.treeview1.heading('#13',text='Log In')
        self.treeview1.heading('#14',text='Observações')
        r1 = Programa.TodosCalibr()
        for i in r1:
            self.treeview1.insert('','end',values=(i))

    def Prevent_view(self):
        self.label3.configure(text='Manutenções Preventivas')
        self.treeview1['columns']=('c1','c2','c3','c4','c5','c6','c7','c8','c9','c10','c11','c12','c13','c14')
        self.treeview1.column('#0',width=0)
        self.treeview1.column('c1',width=100)
        self.treeview1.column('c2',width=100)
        self.treeview1.column('c3',width=100)
        self.treeview1.column('c4',width=100)
        self.treeview1.column('c5',width=130)
        self.treeview1.column('c6',width=100)
        self.treeview1.column('c7',width=100)
        self.treeview1.column('c8',width=100)
        self.treeview1.column('c9',width=130)
        self.treeview1.column('c10',width=100)
        self.treeview1.column('c11',width=130)
        self.treeview1.column('c12',width=130)
        self.treeview1.column('c13',width=100)
        self.treeview1.column('c14',width=100)
        self.treeview1.heading('#0',text='')
        self.treeview1.heading('#1',text='Tipo')
        self.treeview1.heading('#2',text='Patrimônio')
        self.treeview1.heading('#3',text='Número de Série')
        self.treeview1.heading('#4',text='Data de Retirada')
        self.treeview1.heading('#5',text='Acessórios Retirados')
        self.treeview1.heading('#6',text='Andar Retirado')
        self.treeview1.heading('#7',text='Setor Retirado')
        self.treeview1.heading('#8',text='Local Retirado')
        self.treeview1.heading('#9',text='Empresa Responsável')
        self.treeview1.heading('#10',text='Técnico')
        self.treeview1.heading('#11',text='Ordem de Serviço')
        self.treeview1.heading('#12',text='Enfermeira Reponsável')
        self.treeview1.heading('#13',text='Log In')
        self.treeview1.heading('#14',text='Observações')
        r1 = Programa.TodosPreventiva()
        for i in r1:
            self.treeview1.insert('','end',values=(i))

    def Esporadica_view(self):
        self.label3.configure(text='Manutenções Esporádicas')
        self.treeview1['columns']=('c1','c2','c3','c4','c5','c6','c7','c8','c9','c10','c11','c12','c13','c13','c14','c15')
        self.treeview1.column('#0',width=0)
        self.treeview1.column('c1',width=100)
        self.treeview1.column('c2',width=100)
        self.treeview1.column('c3',width=100)
        self.treeview1.column('c4',width=100)
        self.treeview1.column('c5',width=130)
        self.treeview1.column('c6',width=130)
        self.treeview1.column('c7',width=100)
        self.treeview1.column('c8',width=100)
        self.treeview1.column('c9',width=100)
        self.treeview1.column('c10',width=100)
        self.treeview1.column('c11',width=100)
        self.treeview1.column('c12',width=130)
        self.treeview1.column('c13',width=130)
        self.treeview1.column('c14',width=100)
        self.treeview1.column('c15',width=100)
        self.treeview1.heading('#0',text='')
        self.treeview1.heading('#1',text='Tipo')
        self.treeview1.heading('#2',text='Patrimônio')
        self.treeview1.heading('#3',text='Número de Série')
        self.treeview1.heading('#4',text='Data de Retirada')
        self.treeview1.heading('#5',text='Problema Relatado')
        self.treeview1.heading('#6',text='Acessórios Retirados')
        self.treeview1.heading('#7',text='Setor Retirado')
        self.treeview1.heading('#8',text='Setor Retirado')
        self.treeview1.heading('#9',text='Setor Retirado')
        self.treeview1.heading('#10',text='Empresa Responsável')
        self.treeview1.heading('#11',text='Técnico')
        self.treeview1.heading('#12',text='Ordem de Serviço')
        self.treeview1.heading('#13',text='Enfermeira Reponsável')
        self.treeview1.heading('#14',text='Log In')
        self.treeview1.heading('#15',text='Observações')
        r1 = Programa.TodosEsporadica()
        for i in r1:
            self.treeview1.insert('','end',values=(i))

    def Reentrada_view(self):
        self.label3.configure(text='Retornos')
        self.treeview1['columns']=('c1','c2','c3','c4','c5','c6','c7','c8','c9')
        self.treeview1.column('#0',width=0)
        self.treeview1.column('c1',width=100)
        self.treeview1.column('c2',width=100)
        self.treeview1.column('c3',width=100)
        self.treeview1.column('c4',width=130)
        self.treeview1.column('c5',width=100)
        self.treeview1.column('c6',width=100)
        self.treeview1.column('c7',width=100)
        self.treeview1.column('c8',width=100)
        self.treeview1.column('c9',width=100)
        self.treeview1.heading('#0',text='')
        self.treeview1.heading('#1',text='Tipo')
        self.treeview1.heading('#2',text='Patrimônio')
        self.treeview1.heading('#3',text='Número de Série')
        self.treeview1.heading('#4',text='Data de Retorno')
        self.treeview1.heading('#5',text='Motivo')
        self.treeview1.heading('#6',text='Peças Trocadas')
        self.treeview1.heading('#7',text='Responsável')
        self.treeview1.heading('#8',text='Log In')
        self.treeview1.heading('#9',text='Observações')

        r1 = Programa.TodosReentrada()
        for i in r1:
            self.treeview1.insert('','end',values=(i))
    def Movi_view(self):
        self.label3.configure(text='Movimentações')
        self.treeview1['columns']=('c1','c2','c3','c4','c5','c6','c7','c8','c9','c10','c11','c12','c13','c14')
        self.treeview1.column('#0',width=0)
        self.treeview1.column('c1',width=100)
        self.treeview1.column('c2',width=100)
        self.treeview1.column('c3',width=100)
        self.treeview1.column('c4',width=130)
        self.treeview1.column('c5',width=100)
        self.treeview1.column('c6',width=100)
        self.treeview1.column('c7',width=100)
        self.treeview1.column('c8',width=100)
        self.treeview1.column('c9',width=100)
        self.treeview1.column('c10',width=100)
        self.treeview1.column('c11',width=100)
        self.treeview1.column('c12',width=130)
        self.treeview1.column('c13',width=100)
        self.treeview1.column('c14',width=100)
        self.treeview1.heading('#0',text='')
        self.treeview1.heading('#1',text='Tipo')
        self.treeview1.heading('#2',text='Patrimônio')
        self.treeview1.heading('#3',text='Número de Série')
        self.treeview1.heading('#4',text='Data da Movimentação')
        self.treeview1.heading('#5',text='Andar de Origem')
        self.treeview1.heading('#6',text='Setor de Origem')
        self.treeview1.heading('#7',text='Local de Origem')
        self.treeview1.heading('#8',text='Andar de Destino')
        self.treeview1.heading('#9',text='Setor de Destino')
        self.treeview1.heading('#10',text='Local de Destino')
        self.treeview1.heading('#11',text='Acessórios')
        self.treeview1.heading('#12',text='Ordem de Serviço')
        self.treeview1.heading('#13',text='Log In')
        self.treeview1.heading('#14',text='Observações')

        r1 = Programa.TodosMovimentacao()
        for i in r1:
            self.treeview1.insert('','end',values=(i))

    def Desativ_view(self):
        self.label3.configure(text='Desativações')
        self.treeview1['columns']=('c1','c2','c3','c4','c5','c6','c7')
        self.treeview1.column('#0',width=0)
        self.treeview1.column('c1',width=100)
        self.treeview1.column('c2',width=100)
        self.treeview1.column('c3',width=100)
        self.treeview1.column('c4',width=100)
        self.treeview1.column('c5',width=100)
        self.treeview1.column('c6',width=100)
        self.treeview1.column('c7',width=100)
        self.treeview1.heading('#0',text='')
        self.treeview1.heading('#1',text='Patrimônio')
        self.treeview1.heading('#2',text='Número de Série')
        self.treeview1.heading('#3',text='Data de Desativação')
        self.treeview1.heading('#4',text='Motivo da Desativação')
        self.treeview1.heading('#5',text='Número do Processo')
        self.treeview1.heading('#6',text='Log In')
        self.treeview1.heading('#7',text='Observação')
        r1 = Programa.TodosDesativados()
        for i in r1:
            self.treeview1.insert('','end',values=(i))

    def Fabri_view(self):
        self.label3.configure(text='Fabricantes')
        self.treeview1['columns']=('c1','c2','c3','c4','c5','c6','c7','c8','c9','c10','c11','c12')
        self.treeview1.column('#0',width=0)
        self.treeview1.column('c1',width=100)
        self.treeview1.column('c2',width=100)
        self.treeview1.column('c3',width=100)
        self.treeview1.column('c4',width=100)
        self.treeview1.column('c5',width=100)
        self.treeview1.column('c6',width=100)
        self.treeview1.column('c7',width=100)
        self.treeview1.column('c8',width=130)
        self.treeview1.column('c9',width=100)
        self.treeview1.column('c10',width=130)
        self.treeview1.column('c11',width=100)
        self.treeview1.column('c12',width=130)
        self.treeview1.heading('#0',text='')
        self.treeview1.heading('#1',text='Empresa')
        self.treeview1.heading('#2',text='Contato')
        self.treeview1.heading('#3',text='2° Contato')
        self.treeview1.heading('#4',text='E-Mail')
        self.treeview1.heading('#5',text='Endereço')
        self.treeview1.heading('#6',text='CNPJ')
        self.treeview1.heading('#7',text='1° Autorizada')
        self.treeview1.heading('#8',text='Contato 1° Autorizada')
        self.treeview1.heading('#9',text='2° Autorizada')
        self.treeview1.heading('#10',text='Contato 2° Autorizada')
        self.treeview1.heading('#11',text='3° Autorizada')
        self.treeview1.heading('#12',text='Contato 3° Autorizada')
        r1 = Programa.TodosFabri()
        for i in r1:
            self.treeview1.insert('','end',values=(i))

    def run(self):
        self.mainwindow.mainloop()

    def sair(self):
        self.mainwindow.destroy()
            
def abre():
    app = InicialApp()
    app.run()

#abre()
