import os
import tkinter as tk
import tkinter.ttk as ttk
import pygubu
import Programa
import AvisoSucess,AvisoNSucess

PROJECT_PATH = os.path.abspath(os.path.dirname(__file__))
PROJECT_UI = os.path.join(PROJECT_PATH, "JanelaSearch.ui")

class JanelasearchApp:
    def __init__(self, master=None):
        # build ui
        self.toplevel1 = tk.Tk() if master is None else tk.Toplevel(master)
        self.frame2 = tk.Frame(self.toplevel1)
        self.toplevel1.title("Procurar")
        #self.cap_PNG = tk.PhotoImage(file='banguela.PNG')
        #self.label1.configure(cursor='gumby', image=self.cap_PNG)
        #self.label1.place(anchor='nw', height='100', relx='0.013', rely='0.01', width='150', x='0', y='0')
        self.treeview1 = ttk.Treeview(self.frame2)
        self.treeview1.place(anchor='nw', height='615', relx='0.146', rely='0.12', width='1107', x='0', y='0')
        
        self.scrollbar1 = ttk.Scrollbar(self.frame2)
        self.scrollbar1.configure(orient='horizontal',command=self.treeview1.xview)
        self.scrollbar1.place(anchor='nw', relx='0.146', rely='0.977', width='1107', x='0', y='0')
        self.treeview1.configure(xscroll=self.scrollbar1.set)
        
        self.scrollbar2 = ttk.Scrollbar(self.frame2)
        self.scrollbar2.configure(orient='vertical',command=self.treeview1.yview)
        self.scrollbar2.place(anchor='nw', height='615', relx='0.987', rely='0.12', x='0', y='0')
        self.treeview1.configure(yscroll=self.scrollbar2.set)
        
        self.label2 = ttk.Label(self.frame2)
        self.label2.configure(background='#a5d6ef', font='{eras demi itc} 36 ', text='SHProgram')
        self.label2.place(anchor='nw', relx='0.146', rely='0.02', x='0', y='0')
        self.label3 = ttk.Label(self.frame2)
        self.label3.configure(borderwidth='5', font='{arial} 20 {}', relief='groove', text='Procurar')
        self.label3.place(anchor='nw', relx='0.68', rely='0.04', x='0', y='0')

        self.btnEquipFabri = tk.Button(self.frame2)
        self.btnEquipFabri.configure(text='Equipamentos')
        self.btnEquipFabri.place(anchor='nw', relx='0.013', rely='0.152', width='150', x='0', y='0')
        self.btnEquipFabri.configure(command=lambda:[self.limpartree(), self.insertEquipFabri_view()])

        self.btnEquipNomeTec = tk.Button(self.frame2)
        self.btnEquipNomeTec.configure(text='Equipamentos')
        self.btnEquipNomeTec.place(anchor='nw', relx='0.013', rely='0.252', width='150', x='0', y='0')
        self.btnEquipNomeTec.configure(command=lambda:[self.limpartree(), self.insertEquipNomeTec_view()])

        self.btnLocalizar = tk.Button(self.frame2)
        self.btnLocalizar.configure(text='Localizar')
        self.btnLocalizar.place(anchor='nw', relx='0.013', rely='0.352', width='150', x='0', y='0')
        self.btnLocalizar.configure(command=lambda:[self.limpartree(), self.insertLocalizar_view()])
        
        self.btnEquipPatri = tk.Button(self.frame2)
        self.btnEquipPatri.configure(text='Equipamentos')
        self.btnEquipPatri.place(anchor='nw', relx='0.013', rely='0.389', width='150', x='0', y='0')
        self.btnEquipPatri.configure(command=lambda:[self.limpartree(), self.insertEquipPatri_view()])

        self.btnCalibrPatri = tk.Button(self.frame2)
        self.btnCalibrPatri.configure(text='Calibração')
        self.btnCalibrPatri.place(anchor='nw', relx='0.013', rely='0.426', width='150', x='0', y='0')
        self.btnCalibrPatri.configure(command=lambda:[self.limpartree(), self.insertCalibrPatri_view()])

        self.btnPrevPatri = tk.Button(self.frame2)
        self.btnPrevPatri.configure(text='Preventiva')
        self.btnPrevPatri.place(anchor='nw', relx='0.013', rely='0.463', width='150', x='0', y='0')
        self.btnPrevPatri.configure(command=lambda:[self.limpartree(), self.insertPrevPatri_view()])

        self.btnEsporPatri = tk.Button(self.frame2)
        self.btnEsporPatri.configure(text='Esporádica')
        self.btnEsporPatri.place(anchor='nw', relx='0.013', rely='0.5', width='150', x='0', y='0')
        self.btnEsporPatri.configure(command=lambda:[self.limpartree(), self.insertEsporaPatri_view()])

        self.btnMovPatri = tk.Button(self.frame2)
        self.btnMovPatri.configure(text='Movimentação')
        self.btnMovPatri.place(anchor='nw', relx='0.013', rely='0.537', width='150', x='0', y='0')
        self.btnMovPatri.configure(command=lambda:[self.limpartree(), self.insertMovimentacaoPatri_view()])

        
        self.entPatriNumSerie = ttk.Entry(self.frame2)
        _text_ = '''Patrimônio ou N° Série'''
        self.entPatriNumSerie.delete('0', 'end')
        self.entPatriNumSerie.insert('0', _text_)
        self.entPatriNumSerie.place(anchor='nw', relx='0.013', rely='0.32', width='150', x='0', y='0')

        y = Programa.Todos()
        r2 = []
        for i in y:
            if i[4] not in r2:
                r2.append(i[4])

        self.combobox5 = ttk.Combobox(self.frame2)
        self.combobox5.configure(cursor='arrow',state="readonly",values=r2)
        self.combobox5.place(anchor='nw', relx='0.013', rely='0.12', width='150', x='0', y='0')

        x = Programa.Todos()
        r1 = []
        for i in x:
            if i[2] not in r1:
                r1.append(i[2])

        self.combobox3 = ttk.Combobox(self.frame2)
        self.combobox3.configure(cursor='arrow',state="readonly",values=r1)
        self.combobox3.place(anchor='nw', relx='0.013', rely='0.22', width='150', x='0', y='0')
        
        '''self.entNomeTec = ttk.Entry(self.frame2)
        _text_ = ''''''
        self.entNomeTec.delete('0', 'end')
        self.entNomeTec.insert('0', _text_)
        self.entNomeTec.place(anchor='nw', relx='0.013', rely='0.22', width='150', x='0', y='0')'''

        
        self.combobox = ttk.Combobox(self.frame2)
        self.combobox.configure(cursor='arrow',state='readonly',values=list(Programa.ListaAndares()))
        self.combobox.place(anchor='nw', relx='0.013', rely='0.605', width='150', x='0', y='0')
        self.btnAndar = tk.Button(self.frame2)
        self.btnAndar.configure(text='Equipamentos')
        self.btnAndar.place(anchor='nw', relx='0.013', rely='0.637', width='150', x='0', y='0')
        self.btnAndar.configure(command=lambda:[self.limpartree(), self.Andar_view()])
        
        self.combobox1 = ttk.Combobox(self.frame2)
        self.combobox1.configure(cursor='arrow',state='readonly',values=list(Programa.ListaSetores1()))
        self.combobox1.place(anchor='nw', relx='0.013', rely='0.705', width='150', x='0', y='0')
        self.btnSetor = tk.Button(self.frame2)
        self.btnSetor.configure(text='Equipamentos')
        self.btnSetor.place(anchor='nw', relx='0.013', rely='0.737', width='150', x='0', y='0')
        self.btnSetor.configure(command=lambda:[self.limpartree(), self.Setor_view()])

        self.entLocal = ttk.Entry(self.frame2)
        _text_ = '''Local'''
        self.entLocal.delete('0', 'end')
        self.entLocal.insert('0', _text_)
        self.entLocal.place(anchor='nw', relx='0.013', rely='0.805', width='150', x='0', y='0')
        self.btnLocal = tk.Button(self.frame2)
        self.btnLocal.configure(text='Equipamentos')
        self.btnLocal.place(anchor='nw', relx='0.013', rely='0.837', width='150', x='0', y='0')
        self.btnLocal.configure(command=lambda:[self.limpartree(), self.Local_view()])

        self.entHistorico = ttk.Entry(self.frame2)
        _text_ = '''Patrimônio ou N° Série'''
        self.entHistorico.delete('0', 'end')
        self.entHistorico.insert('0', _text_)
        self.entHistorico.place(anchor='nw', relx='0.013', rely='0.905', width='150', x='0', y='0')
        
        self.btnHistorico = tk.Button(self.frame2)
        self.btnHistorico.configure(text='Histórico')
        self.btnHistorico.place(anchor='nw', relx='0.013', rely='0.937', width='150', x='0', y='0')
        self.btnHistorico.configure(command=lambda:[self.limpartree(), self.Hist_view()])

        
        self.frame2.configure(background='#a5d6ef', borderwidth='5', height='730', relief='sunken')
        self.frame2.configure(takefocus=True, width='1330')
        self.frame2.place(anchor='nw', relx='0.003', rely='0.003', x='0', y='0')
        self.toplevel1.configure(background='#669bdb', borderwidth='5', height='700', relief='raised')
        self.toplevel1.configure(takefocus=True, width='1350')
        self.toplevel1.geometry('1350x750')

        app_width =1350
        app_height =750

        screen_width =self.toplevel1.winfo_screenwidth()
        screen_height=self.toplevel1.winfo_screenheight()

        x = (screen_width/2)-(app_width/2)
        y = (screen_height/2)-(app_height/2)

        self.toplevel1.geometry(f'{app_width}x{app_height}+{int(x)}+{int(y)}')


        # Main widget
        self.mainwindow = self.toplevel1
      
    def limpartree(self):
        self.treeview1.delete(*self.treeview1.get_children())

    def run(self):
        self.mainwindow.mainloop()

    def insertEquipPatri_view(self):
        self.label3.configure(text='Equipamentos')
        self.label3.place(anchor='nw', relx='0.68', rely='0.04', x='0', y='0')
        self.treeview1['columns']=('c1','c2','c3','c4','c5','c6','c7','c8','c9','c10','c11','c12','c13','c14','c15','c16','c17','c18','c19','c20','c21','c22','c23','c24','c25','c26','c27','c28')
        self.treeview1.column('#0',width=0)
        self.treeview1.column('c1',width=100)
        self.treeview1.column('c2',width=100)
        self.treeview1.column('c3',width=100)
        self.treeview1.column('c4',width=100)
        self.treeview1.column('c5',width=100)
        self.treeview1.column('c6',width=100)
        self.treeview1.column('c7',width=120)
        self.treeview1.column('c8',width=100)
        self.treeview1.column('c9',width=100)
        self.treeview1.column('c10',width=100)
        self.treeview1.column('c11',width=100)
        self.treeview1.column('c12',width=125)
        self.treeview1.column('c13',width=120)
        self.treeview1.column('c14',width=120)
        self.treeview1.column('c15',width=135)
        self.treeview1.column('c16',width=120)
        self.treeview1.column('c17',width=130)
        self.treeview1.column('c18',width=130)
        self.treeview1.column('c19',width=100)
        self.treeview1.column('c20',width=100)
        self.treeview1.column('c21',width=100)
        self.treeview1.column('c22',width=100)
        self.treeview1.column('c23',width=100)
        self.treeview1.column('c24',width=100)
        self.treeview1.column('c25',width=100)
        self.treeview1.column('c26',width=100)
        self.treeview1.column('c27',width=100)
        self.treeview1.column('c28',width=100)
        self.treeview1.heading('#0',text='')
        self.treeview1.heading('#1',text='Situação')
        self.treeview1.heading('#2',text='Tipo')
        self.treeview1.heading('#3',text='Nome Técnico')
        self.treeview1.heading('#4',text='Modelo')
        self.treeview1.heading('#5',text='Fabricante')
        self.treeview1.heading('#6',text='Nota Fiscal')
        self.treeview1.heading('#7',text='Número de Série')
        self.treeview1.heading('#8',text='Patrimônio')
        self.treeview1.heading('#9',text='Número Anvisa')
        self.treeview1.heading('#10',text='Acessórios')
        self.treeview1.heading('#11',text='Insumos')
        self.treeview1.heading('#12',text='Data De Recebimento')
        self.treeview1.heading('#13',text='Data de Aceitação')
        self.treeview1.heading('#14',text='Data de Instalação')
        self.treeview1.heading('#15',text='Data de Funcionamento')
        self.treeview1.heading('#16',text='Data de Desativação')
        self.treeview1.heading('#17',text='Intervalo de Calibração')
        self.treeview1.heading('#18',text='Intervalo de Preventiva')
        self.treeview1.heading('#19',text='Andar Instalado')
        self.treeview1.heading('#20',text='Setor Instalado')
        self.treeview1.heading('#21',text='Local Instalado')
        self.treeview1.heading('#22',text='Andar Atual')
        self.treeview1.heading('#23',text='Setor Atual')
        self.treeview1.heading('#24',text='Local Atual')
        self.treeview1.heading('#25',text='Treinamento')
        self.treeview1.heading('#26',text='Responsável')
        self.treeview1.heading('#27',text='Observações')
        self.treeview1.heading('#28',text='Log In')
        r1 =Programa.ProcPatri(self.entPatriNumSerie.get())
        for i in r1:
            self.treeview1.insert('','end',values=(i))

    def insertEquipFabri_view(self):
            self.label3.configure(text='Equipamentos')
            self.label3.place(anchor='nw', relx='0.68', rely='0.04', x='0', y='0')
            self.treeview1['columns']=('c1','c2','c3','c4','c5','c6','c7','c8')
            self.treeview1.column('#0',width=0)
            self.treeview1.column('c1',width=100)
            self.treeview1.column('c2',width=100)
            self.treeview1.column('c3',width=100)
            self.treeview1.column('c4',width=100)
            self.treeview1.column('c5',width=100)
            self.treeview1.column('c6',width=100)
            self.treeview1.column('c7',width=100)
            self.treeview1.column('c8',width=100)
            self.treeview1.heading('#0',text='')
            self.treeview1.heading('#1',text='Situação')
            self.treeview1.heading('#2',text='Fabricante')
            self.treeview1.heading('#3',text='Nome Técnico')
            self.treeview1.heading('#4',text='Patrimônio')
            self.treeview1.heading('#5',text='Número de Série')
            self.treeview1.heading('#6',text='Andar Atual')
            self.treeview1.heading('#7',text='Setor Atual')
            self.treeview1.heading('#8',text='Local Atual')
            r1 =Programa.ProcFabri(self.combobox5.get())
            for i in r1:
                self.treeview1.insert('','end',values=(i))

    def insertEquipNomeTec_view(self):
            self.label3.configure(text='Equipamentos')
            self.label3.place(anchor='nw', relx='0.68', rely='0.04', x='0', y='0')
            self.treeview1['columns']=('c1','c2','c3','c4','c5','c6','c7','c8')
            self.treeview1.column('#0',width=0)
            self.treeview1.column('c1',width=100)
            self.treeview1.column('c2',width=100)
            self.treeview1.column('c3',width=100)
            self.treeview1.column('c4',width=100)
            self.treeview1.column('c5',width=100)
            self.treeview1.column('c6',width=100)
            self.treeview1.column('c7',width=100)
            self.treeview1.column('c8',width=100)
            self.treeview1.heading('#0',text='')
            self.treeview1.heading('#1',text='Situação')
            self.treeview1.heading('#2',text='Nome Técnico')
            self.treeview1.heading('#3',text='Modelo')
            self.treeview1.heading('#4',text='Patrimônio')
            self.treeview1.heading('#5',text='Número de Série')
            self.treeview1.heading('#6',text='Andar Atual')
            self.treeview1.heading('#7',text='Setor Atual')
            self.treeview1.heading('#8',text='Local Atual')
            r1 =Programa.ProcNomeTec(self.combobox3.get())
            for i in r1:
                self.treeview1.insert('','end',values=(i))

    def insertLocalizar_view(self):
            self.label3.configure(text='Localizar')
            self.label3.place(anchor='nw', relx='0.68', rely='0.04', x='0', y='0')
            self.treeview1['columns']=('c1','c2','c3','c4','c5','c6','c7')
            self.treeview1.column('#0',width=0)
            self.treeview1.column('c1',width=100)
            self.treeview1.column('c2',width=100)
            self.treeview1.column('c3',width=100)
            self.treeview1.column('c4',width=100)
            self.treeview1.column('c5',width=100)
            self.treeview1.column('c6',width=100)
            self.treeview1.column('c7',width=100)
            self.treeview1.heading('#0',text='')
            self.treeview1.heading('#1',text='Situação')
            self.treeview1.heading('#2',text='Nome Técnico')
            self.treeview1.heading('#3',text='Número de Série')
            self.treeview1.heading('#4',text='Patrimônio')
            self.treeview1.heading('#5',text='Andar Atual')
            self.treeview1.heading('#6',text='Setor Atual')
            self.treeview1.heading('#7',text='Local Atual')
            r1 =Programa.LocalizarEquip(self.entPatriNumSerie.get())
            for i in r1:
                self.treeview1.insert('','end',values=(i))

    def insertCalibrPatri_view(self):
            self.label3.configure(text='Calibração')
            self.label3.place(anchor='nw', relx='0.68', rely='0.04', x='0', y='0')
            self.treeview1['columns']=('c1','c2','c3','c4','c5','c6','c7','c8','c9','c10','c11','c12','c13')
            self.treeview1.column('#0',width=0)
            self.treeview1.column('c1',width=100)
            self.treeview1.column('c2',width=100)
            self.treeview1.column('c3',width=100)
            self.treeview1.column('c4',width=100)
            self.treeview1.column('c5',width=100)
            self.treeview1.column('c6',width=100)
            self.treeview1.column('c7',width=100)
            self.treeview1.column('c8',width=100)
            self.treeview1.column('c9',width=100)
            self.treeview1.column('c10',width=100)
            self.treeview1.column('c11',width=100)
            self.treeview1.column('c12',width=100)
            self.treeview1.column('c13',width=100)
            self.treeview1.heading('#0',text='')
            self.treeview1.heading('#1',text='Tipo')
            self.treeview1.heading('#2',text='Patrimônio')
            self.treeview1.heading('#3',text='Número de Série')
            self.treeview1.heading('#4',text='Data')
            r1 =Programa.CalibrPatriNumSerie(self.entPatriNumSerie.get())
            for i in r1:
                self.treeview1.insert('','end',values=(i))

    def insertPrevPatri_view(self):
            self.label3.configure(text='Manutenções Preventivas')
            self.label3.place(anchor='nw', relx='0.68', rely='0.04', x='0', y='0')
            self.treeview1['columns']=('c1','c2','c3','c4','c5','c6','c7','c8','c9','c10','c11','c12','c13')
            self.treeview1.column('#0',width=0)
            self.treeview1.column('c1',width=100)
            self.treeview1.column('c2',width=100)
            self.treeview1.column('c3',width=100)
            self.treeview1.column('c4',width=100)
            self.treeview1.column('c5',width=100)
            self.treeview1.column('c6',width=100)
            self.treeview1.column('c7',width=100)
            self.treeview1.column('c8',width=100)
            self.treeview1.column('c9',width=100)
            self.treeview1.column('c10',width=100)
            self.treeview1.column('c11',width=100)
            self.treeview1.column('c12',width=100)
            self.treeview1.column('c13',width=100)
            self.treeview1.heading('#0',text='')
            self.treeview1.heading('#1',text='Tipo')
            self.treeview1.heading('#2',text='Patrimônio')
            self.treeview1.heading('#3',text='Número de Série')
            self.treeview1.heading('#4',text='Data')
            r1 =Programa.PrevPatriNumSerie(self.entPatriNumSerie.get())
            for i in r1:
                self.treeview1.insert('','end',values=(i))

    def insertEsporaPatri_view(self):
            self.label3.configure(text='Manutenções Esporádicas')
            self.label3.place(anchor='nw', relx='0.68', rely='0.04', x='0', y='0')
            self.treeview1['columns']=('c1','c2','c3','c4','c5','c6','c7','c8','c9','c10','c11','c12','c13','c14')
            self.treeview1.column('#0',width=0)
            self.treeview1.column('c1',width=100)
            self.treeview1.column('c2',width=100)
            self.treeview1.column('c3',width=100)
            self.treeview1.column('c4',width=100)
            self.treeview1.column('c5',width=100)
            self.treeview1.column('c6',width=100)
            self.treeview1.column('c7',width=100)
            self.treeview1.column('c8',width=100)
            self.treeview1.column('c9',width=100)
            self.treeview1.column('c10',width=100)
            self.treeview1.column('c11',width=100)
            self.treeview1.column('c12',width=100)
            self.treeview1.column('c13',width=100)
            self.treeview1.column('c14',width=100)
            self.treeview1.heading('#0',text='')
            self.treeview1.heading('#1',text='Tipo')
            self.treeview1.heading('#2',text='Patrimônio')
            self.treeview1.heading('#3',text='Número de Série')
            self.treeview1.heading('#4',text='Data')
            r1 =Programa.EsporaPatriNumSerie(self.entPatriNumSerie.get())
            for i in r1:
                self.treeview1.insert('','end',values=(i))


    def insertMovimentacaoPatri_view(self):
            self.label3.configure(text='Movimentações')
            self.label3.place(anchor='nw', relx='0.68', rely='0.04', x='0', y='0')
            self.treeview1['columns']=('c1','c2','c3','c4','c5','c6','c7','c8','c9','c10','c11','c12','c13','c14')
            self.treeview1.column('#0',width=0)
            self.treeview1.column('c1',width=100)
            self.treeview1.column('c2',width=100)
            self.treeview1.column('c3',width=100)
            self.treeview1.column('c4',width=130)
            self.treeview1.column('c5',width=100)
            self.treeview1.column('c6',width=100)
            self.treeview1.column('c7',width=100)
            self.treeview1.column('c8',width=100)
            self.treeview1.column('c9',width=100)
            self.treeview1.column('c10',width=100)
            self.treeview1.column('c11',width=100)
            self.treeview1.column('c12',width=130)
            self.treeview1.column('c13',width=100)
            self.treeview1.column('c13',width=100)
            self.treeview1.heading('#0',text='')
            self.treeview1.heading('#1',text='Tipo')
            self.treeview1.heading('#2',text='Patrimônio')
            self.treeview1.heading('#3',text='Número de Série')
            self.treeview1.heading('#4',text='Data da Movimentação')                    
            self.treeview1.heading('#5',text='Andar Origem')
            self.treeview1.heading('#6',text='Setor Origem')
            self.treeview1.heading('#7',text='Local Origem')
            self.treeview1.heading('#8',text='Andar Destino')
            self.treeview1.heading('#9',text='Setor Destino')
            self.treeview1.heading('#10',text='Local Destino')
            self.treeview1.heading('#11',text='Acessórios')
            self.treeview1.heading('#12',text='Ordem de Serviço') 
            self.treeview1.heading('#13',text='Observações')
            self.treeview1.heading('#14',text='Log In')
            r1 =Programa.MovPatriNumSerie(self.entPatriNumSerie.get())
            for i in r1:
                self.treeview1.insert('','end',values=(i))

    def Andar_view(self):
        self.label3.configure(text='Equipamentos por Andar')
        self.label3.place(anchor='nw', relx='0.68', rely='0.04', x='0', y='0')
        self.treeview1['columns']=('c1','c2','c3','c4','c5','c6','c7','c8','c9','c10','c11','c12','c13','c14','c15','c16','c17','c18','c19','c20','c21','c22','c23','c24','c25','c26','c27','c28')
        self.treeview1.column('#0',width=0)
        self.treeview1.column('c1',width=100)
        self.treeview1.column('c2',width=100)
        self.treeview1.column('c3',width=100)
        self.treeview1.column('c4',width=100)
        self.treeview1.column('c5',width=100)
        self.treeview1.column('c6',width=100)
        self.treeview1.column('c7',width=120)
        self.treeview1.column('c8',width=100)
        self.treeview1.column('c9',width=100)
        self.treeview1.column('c10',width=100)
        self.treeview1.column('c11',width=100)
        self.treeview1.column('c12',width=125)
        self.treeview1.column('c13',width=120)
        self.treeview1.column('c14',width=120)
        self.treeview1.column('c15',width=135)
        self.treeview1.column('c16',width=120)
        self.treeview1.column('c17',width=130)
        self.treeview1.column('c18',width=130)
        self.treeview1.column('c19',width=100)
        self.treeview1.column('c20',width=100)
        self.treeview1.column('c21',width=100)
        self.treeview1.column('c22',width=100)
        self.treeview1.column('c23',width=100)
        self.treeview1.column('c24',width=100)
        self.treeview1.column('c25',width=100)
        self.treeview1.column('c26',width=100)
        self.treeview1.column('c27',width=100)
        self.treeview1.column('c28',width=100)
        self.treeview1.heading('#0',text='')
        self.treeview1.heading('#1',text='Situação')
        self.treeview1.heading('#2',text='Tipo')
        self.treeview1.heading('#3',text='Nome Técnico')
        self.treeview1.heading('#4',text='Modelo')
        self.treeview1.heading('#5',text='Fabricante')
        self.treeview1.heading('#6',text='Nota Fiscal')
        self.treeview1.heading('#7',text='Número de Série')
        self.treeview1.heading('#8',text='Patrimônio')
        self.treeview1.heading('#9',text='Número Anvisa')
        self.treeview1.heading('#10',text='Acessórios')
        self.treeview1.heading('#11',text='Insumos')
        self.treeview1.heading('#12',text='Data De Recebimento')
        self.treeview1.heading('#13',text='Data de Aceitação')
        self.treeview1.heading('#14',text='Data de Instalação')
        self.treeview1.heading('#15',text='Data de Funcionamento')
        self.treeview1.heading('#16',text='Data de Desativação')
        self.treeview1.heading('#17',text='Intervalo de Calibração')
        self.treeview1.heading('#18',text='Intervalo de Preventiva')
        self.treeview1.heading('#19',text='Andar Instalado')
        self.treeview1.heading('#20',text='Setor Instalado')
        self.treeview1.heading('#21',text='Local Instalado')
        self.treeview1.heading('#22',text='Andar Atual')
        self.treeview1.heading('#23',text='Setor Atual')
        self.treeview1.heading('#24',text='Local Atual')
        self.treeview1.heading('#25',text='Treinamento')
        self.treeview1.heading('#26',text='Responsável')
        self.treeview1.heading('#27',text='Observações')
        self.treeview1.heading('#28',text='Log In')
        r1 =Programa.LocalizarEquipAndar(self.combobox.get())
        for i in r1:
            self.treeview1.insert('','end',values=(i))

    def Setor_view(self):
        self.label3.configure(text='Equipamentos por Setor')
        self.label3.place(anchor='nw', relx='0.68', rely='0.04', x='0', y='0')
        self.treeview1['columns']=('c1','c2','c3','c4','c5','c6','c7','c8','c9','c10','c11','c12','c13','c14','c15','c16','c17','c18','c19','c20','c21','c22','c23','c24','c25','c26','c27','c28')
        self.treeview1.column('#0',width=0)
        self.treeview1.column('c1',width=100)
        self.treeview1.column('c2',width=100)
        self.treeview1.column('c3',width=100)
        self.treeview1.column('c4',width=100)
        self.treeview1.column('c5',width=100)
        self.treeview1.column('c6',width=100)
        self.treeview1.column('c7',width=120)
        self.treeview1.column('c8',width=100)
        self.treeview1.column('c9',width=100)
        self.treeview1.column('c10',width=100)
        self.treeview1.column('c11',width=100)
        self.treeview1.column('c12',width=125)
        self.treeview1.column('c13',width=120)
        self.treeview1.column('c14',width=120)
        self.treeview1.column('c15',width=135)
        self.treeview1.column('c16',width=120)
        self.treeview1.column('c17',width=130)
        self.treeview1.column('c18',width=130)
        self.treeview1.column('c19',width=100)
        self.treeview1.column('c20',width=100)
        self.treeview1.column('c21',width=100)
        self.treeview1.column('c22',width=100)
        self.treeview1.column('c23',width=100)
        self.treeview1.column('c24',width=100)
        self.treeview1.column('c25',width=100)
        self.treeview1.column('c26',width=100)
        self.treeview1.column('c27',width=100)
        self.treeview1.column('c28',width=100)
        self.treeview1.heading('#0',text='')
        self.treeview1.heading('#1',text='Situação')
        self.treeview1.heading('#2',text='Tipo')
        self.treeview1.heading('#3',text='Nome Técnico')
        self.treeview1.heading('#4',text='Modelo')
        self.treeview1.heading('#5',text='Fabricante')
        self.treeview1.heading('#6',text='Nota Fiscal')
        self.treeview1.heading('#7',text='Número de Série')
        self.treeview1.heading('#8',text='Patrimônio')
        self.treeview1.heading('#9',text='Número Anvisa')
        self.treeview1.heading('#10',text='Acessórios')
        self.treeview1.heading('#11',text='Insumos')
        self.treeview1.heading('#12',text='Data De Recebimento')
        self.treeview1.heading('#13',text='Data de Aceitação')
        self.treeview1.heading('#14',text='Data de Instalação')
        self.treeview1.heading('#15',text='Data de Funcionamento')
        self.treeview1.heading('#16',text='Data de Desativação')
        self.treeview1.heading('#17',text='Intervalo de Calibração')
        self.treeview1.heading('#18',text='Intervalo de Preventiva')
        self.treeview1.heading('#19',text='Andar Instalado')
        self.treeview1.heading('#20',text='Setor Instalado')
        self.treeview1.heading('#21',text='Local Instalado')
        self.treeview1.heading('#22',text='Andar Atual')
        self.treeview1.heading('#23',text='Setor Atual')
        self.treeview1.heading('#24',text='Local Atual')
        self.treeview1.heading('#25',text='Treinamento')
        self.treeview1.heading('#26',text='Responsável')
        self.treeview1.heading('#27',text='Observações')
        self.treeview1.heading('#28',text='Log In')
        r1 =Programa.LocalizarEquipSetor(self.combobox1.get())
        for i in r1:
            self.treeview1.insert('','end',values=(i))

    def Local_view(self):
        self.label3.configure(text='Equipamentos por Local')
        self.label3.place(anchor='nw', relx='0.68', rely='0.04', x='0', y='0')
        self.treeview1['columns']=('c1','c2','c3','c4','c5','c6','c7','c8','c9','c10','c11','c12','c13','c14','c15','c16','c17','c18','c19','c20','c21','c22','c23','c24','c25','c26','c27','c28')
        self.treeview1.column('#0',width=0)
        self.treeview1.column('c1',width=100)
        self.treeview1.column('c2',width=100)
        self.treeview1.column('c3',width=100)
        self.treeview1.column('c4',width=100)
        self.treeview1.column('c5',width=100)
        self.treeview1.column('c6',width=100)
        self.treeview1.column('c7',width=120)
        self.treeview1.column('c8',width=100)
        self.treeview1.column('c9',width=100)
        self.treeview1.column('c10',width=100)
        self.treeview1.column('c11',width=100)
        self.treeview1.column('c12',width=125)
        self.treeview1.column('c13',width=120)
        self.treeview1.column('c14',width=120)
        self.treeview1.column('c15',width=135)
        self.treeview1.column('c16',width=120)
        self.treeview1.column('c17',width=130)
        self.treeview1.column('c18',width=130)
        self.treeview1.column('c19',width=100)
        self.treeview1.column('c20',width=100)
        self.treeview1.column('c21',width=100)
        self.treeview1.column('c22',width=100)
        self.treeview1.column('c23',width=100)
        self.treeview1.column('c24',width=100)
        self.treeview1.column('c25',width=100)
        self.treeview1.column('c26',width=100)
        self.treeview1.column('c27',width=100)
        self.treeview1.column('c28',width=100)
        self.treeview1.heading('#0',text='')
        self.treeview1.heading('#1',text='Situação')
        self.treeview1.heading('#2',text='Tipo')
        self.treeview1.heading('#3',text='Nome Técnico')
        self.treeview1.heading('#4',text='Modelo')
        self.treeview1.heading('#5',text='Fabricante')
        self.treeview1.heading('#6',text='Nota Fiscal')
        self.treeview1.heading('#7',text='Número de Série')
        self.treeview1.heading('#8',text='Patrimônio')
        self.treeview1.heading('#9',text='Número Anvisa')
        self.treeview1.heading('#10',text='Acessórios')
        self.treeview1.heading('#11',text='Insumos')
        self.treeview1.heading('#12',text='Data De Recebimento')
        self.treeview1.heading('#13',text='Data de Aceitação')
        self.treeview1.heading('#14',text='Data de Instalação')
        self.treeview1.heading('#15',text='Data de Funcionamento')
        self.treeview1.heading('#16',text='Data de Desativação')
        self.treeview1.heading('#17',text='Intervalo de Calibração')
        self.treeview1.heading('#18',text='Intervalo de Preventiva')
        self.treeview1.heading('#19',text='Andar Instalado')
        self.treeview1.heading('#20',text='Setor Instalado')
        self.treeview1.heading('#21',text='Local Instalado')
        self.treeview1.heading('#22',text='Andar Atual')
        self.treeview1.heading('#23',text='Setor Atual')
        self.treeview1.heading('#24',text='Local Atual')
        self.treeview1.heading('#25',text='Treinamento')
        self.treeview1.heading('#26',text='Responsável')
        self.treeview1.heading('#27',text='Observações')
        self.treeview1.heading('#28',text='Log In')
        r1 =Programa.LocalizarEquipLocal(self.entLocal.get())
        for i in r1:
            self.treeview1.insert('','end',values=(i))


    def Hist_view(self):
        x = 'Histórico ' + 'Aparelho ' +str(self.entHistorico.get())
        self.label3.configure(text=x)
        self.label3.place(anchor='nw', relx='0.65', rely='0.04', x='0', y='0')
        self.treeview1['columns']=('c1','c2','c3','c4','c5','c6','c7','c8','c9','c10','c11','c12','c13','c14','c15','c16','c17','c18','c19')
        self.treeview1.column('#0',width=0)
        self.treeview1.column('c1',width=100)
        self.treeview1.column('c2',width=100)
        self.treeview1.column('c3',width=100)
        self.treeview1.column('c4',width=100)
        self.treeview1.column('c5',width=100)
        self.treeview1.column('c6',width=100)
        self.treeview1.column('c7',width=100)
        self.treeview1.column('c8',width=100)
        self.treeview1.column('c9',width=100)
        self.treeview1.column('c10',width=100)
        self.treeview1.column('c11',width=100)
        self.treeview1.column('c12',width=100)
        self.treeview1.column('c13',width=100)
        self.treeview1.column('c14',width=100)
        self.treeview1.column('c15',width=100)
        self.treeview1.column('c16',width=100)
        self.treeview1.column('c17',width=100)
        self.treeview1.column('c18',width=100)
        self.treeview1.column('c19',width=100)
        r1 = Programa.Historico(self.entHistorico.get())
        for i in r1:
            self.treeview1.insert('','end',values=(i))


 
def abre():
    app = JanelasearchApp()
    app.run()

#abre()
